export const carNameList = [
    'ambulance',
    // 'box',
    // 'cone-flat',
    // 'cone',
    // 'debris-bolt',
    // 'debris-bumper',
    // 'debris-door-window',
    // 'debris-door',
    // 'debris-drivetrain-axle',
    // 'debris-drivetrain',
    // 'debris-nut',
    // 'debris-plate-a',
    // 'debris-plate-b',
    // 'debris-plate-small-a',
    // 'debris-plate-small-b',
    // 'debris-spoiler-a',
    // 'debris-spoiler-b',
    // 'debris-tire',
    'delivery-flat',
    'delivery',
    'firetruck',
    'garbage-truck',
    'hatchback-sports',
    'police',
    'race-future',
    'race',
    'sedan-sports',
    'sedan',
    'suv-luxury',
    'suv',
    'taxi',
    'tractor-police',
    'tractor-shovel',
    'tractor',
    'truck-flat',
    'truck',
    'van',
    // 'wheel-dark',
    // 'wheel-default',
    // 'wheel-racing',
    // 'wheel-tractor-back',
    // 'wheel-tractor-dark-back',
    // 'wheel-tractor-dark-front',
    // 'wheel-tractor-front',
    // 'wheel-truck',
  ];