export const roadNameList = [
  // 'bridge_pillar',
  // 'bridge_pillarWide',
  // 'construction_barrier',
  // 'construction_light',
  // 'construction_pylon',
  // 'light_curved',
  // 'light_curvedCross',
  // 'light_curvedDouble',
  // 'light_square',
  // 'light_squareCross',
  // 'light_squareDouble',
  'road_bend',
  // 'road_bendBarrier',
  // 'road_bendSidewalk',
  // 'road_bendSquare',
  // 'road_bendSquareBarrier',
  // 'road_bridge',
  'road_crossing',
  'road_crossroad',
  // 'road_crossroadBarrier',
  'road_crossroadLine',
  'road_crossroadPath',
  'road_curve',
  // 'road_curveBarrier',
  'road_curveIntersection',
  // 'road_curveIntersectionBarrier',
  // 'road_curvePavement',
  // 'road_drivewayDouble',
  // 'road_drivewayDoubleBarrier',
  // 'road_drivewaySingle',
  // 'road_drivewaySingleBarrier',
  'road_end',
  // 'road_endBarrier',
  'road_endRound',
  // 'road_endRoundBarrier',
  'road_intersection',
  // 'road_intersectionBarrier',
  // 'road_intersectionLine',
  'road_intersectionPath',
  'road_roundabout',
  // 'road_roundaboutBarrier',
  'road_side',
  // 'road_sideBarrier',
  'road_sideEntry',
  // 'road_sideEntryBarrier',
  'road_sideExit',
  // 'road_sideExitBarrier',
  'road_slant',
  // 'road_slantBarrier',
  'road_slantCurve',
  // 'road_slantCurveBarrier',
  'road_slantFlat',
  'road_slantFlatCurve',
  'road_slantFlatHigh',
  'road_slantHigh',
  // 'road_slantHighBarrier',
  'road_split',
  // 'road_splitBarrier',
  // 'road_square',
  // 'road_squareBarrier',
  'road_straight',
  // 'road_straightBarrier',
  // 'road_straightBarrierEnd',
  'tile_high',
  'tile_low',
  'tile_slant',
  'tile_slantHigh'
];